export const metadata = {
    title: 'Next.js - Auth',
    description: 'Generated by Next.js',
}

export default function AuthLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body>
                {children}

                <footer style={{backgroundColor: "lightblue", padding: "1rem"}}>
                    <p>Footer</p>
                </footer>
            </body>
        </html>
    )
}
