"use client";

import Link from 'next/link';
import {usePathname} from "next/navigation";
import  "./styles.css"

// export const metadata = {
//     title: 'Next.js - Auth',
//     description: 'Generated by Next.js',
// }

const navLinks = [
    { href: '/login', name: 'Login' },
    { href: '/register', name: 'Register' },
    { href: '/forgot-password', name: 'Forgot Password' },
];

export default function AuthLayout({
    children,
}: {
    children: React.ReactNode
}) {
    const pathname = usePathname();

    return (
        <html lang="en">
            <body>
            {
                navLinks.map((link) => {
                    const isActive = pathname === link.href
                    || (pathname.startsWith(link.href) && link.href !=="/");

                    return (
                        <Link
                            className={isActive ? 'font-bold mr-4' : 'text-blue-500 mr-4'}
                            href={link.href}
                            key={link.href}
                        >
                            {link.name}
                        </Link>
                    );
                })
            }

                {children}

                <footer style={{backgroundColor: "lightblue", padding: "1rem"}}>
                    <p>Footer</p>
                </footer>
            </body>
        </html>
    )
}
