export const metadata = {
    title: 'Next.js - About',
    description: 'Generated by Next.js',
    robots: 'index,follow,all,max-image-preview:large',
    keywords: 'about,company,information'
}

export default function About(){
    return <h1>About</h1>;
}