import { Metadata} from "next";

export const metadata: Metadata = {
  title: {
    default: 'Next.js Dominic tutorial',
      template: '%s | Next.js Dominic tutorial',
      absolute: 'Next.js Dominic tutorial',
  },
  description: 'Generated by Next.js',
}

export default function MarketingLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{backgroundColor: "lightblue", padding: "1rem"}}>
            <p>Header</p>
        </header>
      {children}

      <footer style={{backgroundColor: "lightblue", padding: "1rem"}}>
          <p>Footer</p>
      </footer>
      </body>
    </html>
  )
}
