import { Metadata } from "next";

export const metadata: Metadata = {
    title: {
        default: 'Blog',
        absolute: '',
    },
    description: 'Generated by Next.js',
}

export default async function Blog(){
    await  new Promise((resolve) => {
        setTimeout(() => {
            resolve("delay...");
        }, 2000);
    });

    return <h1>Blog</h1>;
}