import { Metadata } from "next";

export const metadata: Metadata = {
    title: {
        default: 'Blog',
        absolute: '',
    },
    description: 'Generated by Next.js',
}

export default function Blog(){
    return <h1>Blog</h1>;
}